version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/entrypoint:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - weaver-network

  server:
    build:
      context: ./ # path of root directory; don't change.
      dockerfile: ./server/Dockerfile # path relative to root directory.
    restart: "no"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:?error}
      POSTGRES_PORT: ${POSTGRES_PORT:?error}
      POSTGRES_DB: ${POSTGRES_DB:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    networks:
      - weaver-network
    depends_on:
      - postgres

networks:
  weaver-network:
    name: weaver-network
